"""
Django settings for scanner project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

from pathlib import Path
import secrets
import os
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except (
    ImportError
):  # The app remains usable when environment variables are set by the OS.
    load_dotenv = None

# ==========================================================
# BASE DIRECTORY
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Local convenience only: production may instead inject environment variables
# through its service manager. `.env` is ignored by source control and must
# never be packaged or shared.
if load_dotenv:
    load_dotenv(BASE_DIR / ".env")

# ==========================================================
# SECURITY
# ==========================================================
# Per the platform's "environment-based secrets" requirement, the secret
# key, debug flag, and allowed hosts are now read from the environment.
# Safe local-development fallbacks are kept so `manage.py runserver` still
# works out of the box; production deployments MUST set these explicitly.
#
#   VIGILANT_SECRET_KEY   - Django secret key (required in production)
#   VIGILANT_DEBUG        - "true"/"false" (defaults to "true" for local dev)
#   VIGILANT_ALLOWED_HOSTS - comma-separated hostnames (defaults to "*" only
#                            while DEBUG is on; production must set this)

DEBUG = os.environ.get("VIGILANT_DEBUG", "true").strip().lower() == "true"

SECRET_KEY = os.environ.get("VIGILANT_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "VIGILANT_SECRET_KEY must be set when VIGILANT_DEBUG is false."
        )
    # Development only: a local, deterministic key avoids placing a reusable
    # secret in source control. Set VIGILANT_SECRET_KEY for every deployment.
    SECRET_KEY = secrets.token_urlsafe(64)

_allowed_hosts_env = os.environ.get("VIGILANT_ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    # Fail safe: without an explicit host list, refuse to serve requests
    # in production rather than silently accepting any Host header.
    ALLOWED_HOSTS = []

# Threat-intelligence provider keys (see myapp/scan_engine.py:threat_intel_lookup).
# Left unset by default -> the app reports "local analysis only" honestly
# instead of fabricating external results.
VT_API_KEY = os.environ.get("VT_API_KEY", "")
ABUSEIPDB_API_KEY = os.environ.get("ABUSEIPDB_API_KEY", "")

# CAPTCHA (see myapp/captcha.py). Unset by default -> login/register run in
# an explicitly-labeled development mode instead of a fake protected form.
CAPTCHA_PROVIDER = os.environ.get("CAPTCHA_PROVIDER", "turnstile").strip().lower()
CAPTCHA_SITE_KEY = os.environ.get("CAPTCHA_SITE_KEY", "")
CAPTCHA_SECRET_KEY = os.environ.get("CAPTCHA_SECRET_KEY", "")

if not DEBUG:
    # Baseline hardening for non-debug deployments. These are safe no-ops
    # in local HTTP development because DEBUG defaults to true above.
    SECURE_SSL_REDIRECT = (
        os.environ.get("VIGILANT_SSL_REDIRECT", "true").strip().lower() == "true"
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# ==========================================================
# APPLICATIONS
# ==========================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myapp",
]

# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [
    "myapp.presentation.CapabilityDisplayMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "myapp.middleware.AuthenticationThrottle",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ==========================================================
# URL CONFIGURATION
# ==========================================================

ROOT_URLCONF = "scanner.urls"

# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "myapp.context.site_context",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ==========================================================
# WSGI
# ==========================================================

WSGI_APPLICATION = "scanner.wsgi.application"

# ==========================================================
# DATABASE
# ==========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("VIGILANT_DB_PATH", BASE_DIR / "db.sqlite3"),
    }
}

# ==========================================================
# CUSTOM USER MODEL
# ==========================================================

AUTH_USER_MODEL = "myapp.CustomUser"

# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# ==========================================================
# STATIC FILES
# ==========================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"

# ==========================================================
# MEDIA FILES
# ==========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# ==========================================================
# LOGIN / LOGOUT
# ==========================================================

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "/dashboard/"

LOGOUT_REDIRECT_URL = "/login/"

# ==========================================================
# DEFAULT PRIMARY KEY
# ==========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==========================================================
# AEGIS ENGINE DIRECTORIES
# ==========================================================

REPORT_DIR = BASE_DIR / "reports"

QUARANTINE_DIR = BASE_DIR / "quarantine"

THREAT_DB_DIR = BASE_DIR / "threat_database"

IOC_DIR = BASE_DIR / "ioc_data"

LOG_DIR = BASE_DIR / "logs"

for directory in [REPORT_DIR, QUARANTINE_DIR, THREAT_DB_DIR, IOC_DIR, LOG_DIR]:
    os.makedirs(directory, exist_ok=True)

# ==========================================================
# FILE MONITORING
# ==========================================================

MONITORED_DIRECTORIES = [
    str(Path.home() / "Downloads"),
    str(Path.home() / "Desktop"),
    str(Path.home() / "Documents"),
]

# ==========================================================
# THREAT INTELLIGENCE
# ==========================================================
# Keys are intentionally read only from the environment.  Do not replace
# these with literals: integrations must accurately report Not Configured
# until an operator provides credentials.
OTX_API_KEY = os.environ.get("OTX_API_KEY", "")
HIBP_API_KEY = os.environ.get("HIBP_API_KEY", "")
HIBP_EMAIL_CHECK_ENABLED = (
    os.environ.get("HIBP_EMAIL_CHECK_ENABLED", "true").strip().lower() == "true"
)
HIBP_EMAIL_TIMEOUT = int(os.environ.get("HIBP_EMAIL_TIMEOUT", "10"))
HIBP_EMAIL_MODE = os.environ.get("HIBP_EMAIL_MODE", "direct").strip().lower()
HIBP_PASSWORDS_ENABLED = (
    os.environ.get("HIBP_PASSWORDS_ENABLED", "true").strip().lower() == "true"
)
PASSWORD_ANALYZER_ENABLED = (
    os.environ.get("PASSWORD_ANALYZER_ENABLED", "true").strip().lower() == "true"
)
PASSWORD_GENERATOR_ENABLED = (
    os.environ.get("PASSWORD_GENERATOR_ENABLED", "true").strip().lower() == "true"
)
PASSWORD_MAX_LENGTH = int(os.environ.get("PASSWORD_MAX_LENGTH", "256"))
PASSWORD_BREACH_TIMEOUT = int(os.environ.get("PASSWORD_BREACH_TIMEOUT", "10"))

# Target investigations are bounded to prevent the application becoming a proxy
# or an uncontrolled scanner. Values are deliberately conservative.
TARGET_HTTP_TIMEOUT = int(os.environ.get("VIGILANT_TARGET_HTTP_TIMEOUT", "10"))
TARGET_HTTP_MAX_BYTES = int(
    os.environ.get("VIGILANT_TARGET_HTTP_MAX_BYTES", str(1024 * 1024))
)
TARGET_REDIRECT_LIMIT = int(os.environ.get("VIGILANT_TARGET_REDIRECT_LIMIT", "5"))
TARGET_SCAN_LIMIT_PER_HOUR = int(
    os.environ.get("VIGILANT_TARGET_SCAN_LIMIT_PER_HOUR", "30")
)

PASSWORD_ATTACK_PROFILES = {
    "online_throttled": {
        "label": "Online attack (throttled)",
        "guesses_per_second": int(
            os.environ.get("PASSWORD_GPS_ONLINE_THROTTLED", "10")
        ),
    },
    "online_fast": {
        "label": "Online attack (fast)",
        "guesses_per_second": int(os.environ.get("PASSWORD_GPS_ONLINE_FAST", "10000")),
    },
    "offline_slow": {
        "label": "Offline attack (slow hash)",
        "guesses_per_second": int(
            os.environ.get("PASSWORD_GPS_OFFLINE_SLOW", "100000")
        ),
    },
    "offline_fast": {
        "label": "Offline attack (fast hash)",
        "guesses_per_second": int(
            os.environ.get("PASSWORD_GPS_OFFLINE_FAST", "10000000000")
        ),
    },
    "gpu_attack": {
        "label": "GPU attack",
        "guesses_per_second": int(os.environ.get("PASSWORD_GPS_GPU", "100000000000")),
    },
    "botnet_attack": {
        "label": "Botnet attack",
        "guesses_per_second": int(
            os.environ.get("PASSWORD_GPS_BOTNET", "1000000000000")
        ),
    },
}

# Critical alert delivery. Passwords remain environment-only and are never
# rendered, serialized, or stored in the database.
VIGILANT_SMTP_HOST = os.environ.get("VIGILANT_SMTP_HOST", "")
VIGILANT_SMTP_PORT = int(os.environ.get("VIGILANT_SMTP_PORT", "587"))
VIGILANT_SMTP_USERNAME = os.environ.get("VIGILANT_SMTP_USERNAME", "")
VIGILANT_SMTP_PASSWORD = os.environ.get("VIGILANT_SMTP_PASSWORD", "")
VIGILANT_SMTP_USE_TLS = (
    os.environ.get("VIGILANT_SMTP_USE_TLS", "true").strip().lower() == "true"
)
VIGILANT_SMTP_USE_SSL = (
    os.environ.get("VIGILANT_SMTP_USE_SSL", "false").strip().lower() == "true"
)
VIGILANT_ALERT_FROM_EMAIL = os.environ.get("VIGILANT_ALERT_FROM_EMAIL", "")
VIGILANT_ALERT_RECIPIENTS = os.environ.get("VIGILANT_ALERT_RECIPIENTS", "")
OPENPHISH_URL = os.environ.get("OPENPHISH_URL", "https://openphish.com/feed.txt")

# Static upload policy. Uploaded samples are analyzed in memory only by the
# current local analyzer and are never executed or extracted.
MAX_UPLOAD_SIZE = int(os.environ.get("VIGILANT_MAX_UPLOAD_SIZE", 25 * 1024 * 1024))

# ==========================================================
# SECURITY ANALYTICS
# ==========================================================

MAX_RISK_SCORE = 100

CRITICAL_THRESHOLD = 90

HIGH_THRESHOLD = 70

MEDIUM_THRESHOLD = 40

LOW_THRESHOLD = 20

# ==========================================================
# FILE INTEGRITY MONITORING
# ==========================================================

FIM_HASH_ALGORITHM = "sha256"

FIM_BASELINE_FILE = BASE_DIR / "fim_baseline.json"

# ==========================================================
# MITRE ATT&CK
# ==========================================================

ENABLE_MITRE_MAPPING = True

MITRE_ATTACK_VERSION = "19.2"

# ==========================================================
# IOC CORRELATION
# ==========================================================

ENABLE_IOC_CORRELATION = True

IOC_MATCH_THRESHOLD = 80

# ==========================================================
# INCIDENT MANAGEMENT
# ==========================================================

AUTO_CREATE_INCIDENTS = True

# Destructive responses are never automatic.  A future response worker must
# require an approved action and honor DRY_RUN before changing an endpoint.
AUTO_QUARANTINE_CRITICAL = False
RESPONSE_DRY_RUN = (
    os.environ.get("VIGILANT_RESPONSE_DRY_RUN", "true").strip().lower() == "true"
)

AUTO_CLOSE_RESOLVED_INCIDENTS = False

# ==========================================================
# TIMELINE
# ==========================================================

TIMELINE_RETENTION_DAYS = 90

# ==========================================================
# YARA RULES
# ==========================================================

YARA_RULES_DIR = BASE_DIR / "yara_rules"

os.makedirs(YARA_RULES_DIR, exist_ok=True)

# ==========================================================
# SIGMA RULES
# ==========================================================

SIGMA_RULES_DIR = BASE_DIR / "sigma_rules"

os.makedirs(SIGMA_RULES_DIR, exist_ok=True)

# ==========================================================
# EVENT LOG ANALYSIS
# ==========================================================

ENABLE_EVENT_LOG_ANALYSIS = True

# ==========================================================
# LOGGING
# ==========================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "aegis.log",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

# Optional public links are deliberately empty until configured.
DEVELOPER_GITHUB_URL = os.getenv("DEVELOPER_GITHUB_URL", "")
DEVELOPER_LINKEDIN_URL = os.getenv("DEVELOPER_LINKEDIN_URL", "")
VIGILANT_SPHERE_GITHUB_URL = os.getenv("VIGILANT_SPHERE_GITHUB_URL", "")
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
PASSWORD_RESET_TIMEOUT = 1800
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = VIGILANT_SMTP_HOST
EMAIL_PORT = VIGILANT_SMTP_PORT
EMAIL_HOST_USER = VIGILANT_SMTP_USERNAME
EMAIL_HOST_PASSWORD = VIGILANT_SMTP_PASSWORD
EMAIL_USE_TLS = VIGILANT_SMTP_USE_TLS
EMAIL_USE_SSL = VIGILANT_SMTP_USE_SSL
DEFAULT_FROM_EMAIL = VIGILANT_ALERT_FROM_EMAIL or "noreply@localhost"

# Do not persist request paths, exception context or submitted credentials in logs.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"null": {"class": "logging.NullHandler"}},
    "loggers": {
        "django.request": {"handlers": ["null"], "propagate": False},
        "django.server": {"handlers": ["null"], "propagate": False},
    },
    "root": {"handlers": ["null"], "level": "WARNING"},
}

if not DEBUG:
    SECURE_HSTS_SECONDS = 3600

IOC_EXPIRY_DAYS = int(os.environ.get("IOC_EXPIRY_DAYS", "90"))
IOC_MIN_DETECTIONS = int(os.environ.get("IOC_MIN_DETECTIONS", "3"))
IOC_MIN_ABUSE_SCORE = int(os.environ.get("IOC_MIN_ABUSE_SCORE", "80"))

IOC_MIN_OTX_PULSES = int(os.environ.get("IOC_MIN_OTX_PULSES", "3"))
