# Generated by Django 4.2.30 on 2026-09-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_attackpatterndetection_behavioralthreat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('MACOS', 'macOS'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('version', models.CharField(default='prototype', max_length=80)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('UNENROLLED', 'Unenrolled')], default='UNENROLLED', max_length=30)),
                ('capabilities', models.JSONField(default=list)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='myapp.assetinventory')),
            ],
        ),
        migrations.CreateModel(
            name='USBDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=128, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=160)),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('serial_number_hash', models.CharField(blank=True, max_length=128)),
                ('filesystem', models.CharField(blank=True, max_length=80)),
                ('capacity_bytes', models.BigIntegerField(default=0)),
                ('trust_state', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('TRUSTED', 'Trusted'), ('RESTRICTED', 'Restricted'), ('BLOCKED', 'Blocked')], default='UNKNOWN', max_length=30)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USBScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=30)),
                ('files_discovered', models.IntegerField(default=0)),
                ('files_scanned', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('threat_count', models.IntegerField(default=0)),
                ('policy_violations', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('severity', models.CharField(default='LOW', max_length=30)),
                ('confidence', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('QUARANTINE', 'Quarantine')], default='ALLOW', max_length=30)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='myapp.usbdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='USBScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=120)),
                ('sha256', models.CharField(blank=True, max_length=128)),
                ('detection_rule', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(default='LOW', max_length=30)),
                ('confidence', models.IntegerField(default=0)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='myapp.usbscanjob')),
            ],
        ),
        migrations.CreateModel(
            name='USBConnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_point', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('SCAN_REQUESTED', 'Scan Requested'), ('POLICY_BLOCKED', 'Policy Blocked')], default='SCAN_REQUESTED', max_length=40)),
                ('policy_result', models.CharField(default='Require Scan', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.endpointagent')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_events', to='myapp.usbdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=240)),
                ('target', models.CharField(blank=True, max_length=240)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('scope', models.CharField(default='global', max_length=80)),
                ('environment', models.CharField(default='development', max_length=80)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointTelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='INFO', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='myapp.endpointagent')),
            ],
        ),
    ]
