# Generated by Django 5.2.14 on 2026-09-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_endpointagent_usbdevice_usbscanjob_usbscanfinding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('application_type', models.CharField(choices=[('USER_APP', 'User Application'), ('ADMIN_APP', 'Admin Application')], max_length=30)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('MACOS', 'macOS')], default='ANDROID', max_length=30)),
                ('version', models.CharField(default='1.0.0', max_length=60)),
                ('release_notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='application_releases/')),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('file_size', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('required_role', models.CharField(default='USER', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMSAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=260)),
                ('announcement_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('CRITICAL', 'Critical')], default='INFO', max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=260)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMSBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(default='text', max_length=60)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CMSBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(default='Security', max_length=80)),
                ('tags', models.CharField(blank=True, max_length=240)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('reading_time', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SCHEDULED', 'Scheduled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CMSDeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(default='Dhithimos E J', max_length=180)),
                ('short_bio', models.CharField(blank=True, max_length=320)),
                ('full_bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMSMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='cms_media/')),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('caption', models.CharField(blank=True, max_length=260)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CMSNavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=260)),
                ('location', models.CharField(default='main', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['location', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('seo_keywords', models.CharField(blank=True, max_length=320)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SCHEDULED', 'Scheduled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('search_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CMSPageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('change_summary', models.CharField(blank=True, max_length=260)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='myapp.cmspage')),
            ],
        ),
        migrations.CreateModel(
            name='CMSSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vigilant Sphere', max_length=180)),
                ('default_seo_title', models.CharField(blank=True, max_length=220)),
                ('default_seo_description', models.CharField(blank=True, max_length=320)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('footer_text', models.CharField(default='Vigilant Sphere Security Intelligence Platform', max_length=260)),
                ('maintenance_notice', models.CharField(blank=True, max_length=260)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FalsePositiveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('NEEDS_REVIEW', 'Needs Review')], default='NEEDS_REVIEW', max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('previous_score', models.IntegerField(default=0)),
                ('updated_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_positive_reviews', to='myapp.scanresult')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='endpointagent',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='endpointtelemetryevent',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='usbconnectionevent',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='usbconnectionevent',
            name='device',
        ),
        migrations.RemoveField(
            model_name='usbconnectionevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usbscanjob',
            name='device',
        ),
        migrations.DeleteModel(
            name='USBDeviceActivity',
        ),
        migrations.RemoveField(
            model_name='usbscanfinding',
            name='job',
        ),
        migrations.RemoveField(
            model_name='usbscanjob',
            name='user',
        ),
        migrations.AddField(
            model_name='cmsdeveloperprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.cmsmedia'),
        ),
        migrations.AddField(
            model_name='cmsblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='myapp.cmspage'),
        ),
        migrations.DeleteModel(
            name='EndpointTelemetryEvent',
        ),
        migrations.DeleteModel(
            name='EndpointAgent',
        ),
        migrations.DeleteModel(
            name='USBConnectionEvent',
        ),
        migrations.DeleteModel(
            name='USBDevice',
        ),
        migrations.DeleteModel(
            name='USBScanFinding',
        ),
        migrations.DeleteModel(
            name='USBScanJob',
        ),
    ]
