from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("myapp", "0010_targetscan")]
    operations = [
        migrations.CreateModel(name="AlertEmailConfiguration", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("enabled", models.BooleanField(default=False)), ("host", models.CharField(blank=True, max_length=255)), ("port", models.PositiveIntegerField(default=587)), ("use_tls", models.BooleanField(default=True)), ("use_ssl", models.BooleanField(default=False)), ("from_email", models.EmailField(blank=True, max_length=254)), ("recipients", models.TextField(blank=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="WiFiAudit", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("profile_name", models.CharField(max_length=512)), ("authentication", models.CharField(blank=True, max_length=120)), ("encryption", models.CharField(blank=True, max_length=120)), ("security_level", models.CharField(default="UNKNOWN", max_length=32)), ("risk_level", models.CharField(default="UNKNOWN", max_length=16)), ("risk_score", models.PositiveSmallIntegerField(default=0)), ("risk_reason", models.TextField(blank=True)), ("recommendation", models.TextField(blank=True)), ("collection_status", models.CharField(default="AVAILABLE", max_length=32)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name="wifi_audits", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="SecurityAlertDelivery", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed"), ("NOT_CONFIGURED", "Not configured")], default="PENDING", max_length=32)), ("recipient_count", models.PositiveIntegerField(default=0)), ("delivery_attempts", models.PositiveSmallIntegerField(default=0)), ("error", models.CharField(blank=True, max_length=500)), ("sent_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("alert", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="email_delivery", to="myapp.securityalert"))]),
        migrations.AddIndex(model_name="wifiaudit", index=models.Index(fields=["user", "created_at"], name="myapp_wifi__user_id_f5e3c1_idx")),
        migrations.AddIndex(model_name="wifiaudit", index=models.Index(fields=["risk_level", "created_at"], name="myapp_wifi__risk_le_e3a99a_idx")),
    ]
