# Generated by Django 5.2.14 on 2026-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wifi_email_alerts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='targetscan',
            new_name='myapp_targe_user_id_a82fb5_idx',
            old_name='myapp_targe_user_id_4e7e46_idx',
        ),
        migrations.RenameIndex(
            model_name='targetscan',
            new_name='myapp_targe_target__b5a386_idx',
            old_name='myapp_targe_target__02af4e_idx',
        ),
        migrations.RenameIndex(
            model_name='wifiaudit',
            new_name='myapp_wifia_user_id_c92fc0_idx',
            old_name='myapp_wifi__user_id_f5e3c1_idx',
        ),
        migrations.RenameIndex(
            model_name='wifiaudit',
            new_name='myapp_wifia_risk_le_221301_idx',
            old_name='myapp_wifi__risk_le_e3a99a_idx',
        ),
        migrations.AlterField(
            model_name='alertemailconfiguration',
            name='recipients',
            field=models.TextField(blank=True, help_text='One email address per line or comma-separated.'),
        ),
    ]
