# Generated by Django 5.2.14 on 2026-09-20 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_myapp_targe_user_id_4e7e46_idx_myapp_targe_user_id_a82fb5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='findings',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='myapp.finding'),
        ),
        migrations.AddField(
            model_name='incident',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incident',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='target',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='targetscan',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation', to='myapp.scanjob'),
        ),
    ]
