# Generated by Django 5.2.17 on 2026-09-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_finding_updated_at_incident_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='scan_jobs',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='myapp.scanjob'),
        ),
    ]
