# Generated by Django 5.2.17 on 2026-09-21 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_incident_scan_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertemailconfiguration',
            name='alert_dedup_window_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='alertemailconfiguration',
            name='alert_severity_threshold',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High')], default='CRITICAL', max_length=8),
        ),
        migrations.AddField(
            model_name='alertemailconfiguration',
            name='digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertemailconfiguration',
            name='digest_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=8),
        ),
        migrations.AddField(
            model_name='alertemailconfiguration',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=600),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiaudit',
            name='bssid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='wifiaudit',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_audits', to='myapp.finding'),
        ),
        migrations.AddField(
            model_name='wifiaudit',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TrustedWifiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=512)),
                ('security_level_at_trust', models.CharField(max_length=32)),
                ('risk_score_at_trust', models.PositiveSmallIntegerField()),
                ('trusted_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'profile_name'), name='unique_trusted_wifi_user_profile')],
            },
        ),
    ]
