# Generated by Django 5.2.17 on 2026-09-21 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alertemailconfiguration_alert_dedup_window_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('content_type', models.CharField(max_length=80)),
                ('data', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationRelease',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='phase',
            field=models.CharField(choices=[('TRIAGE', 'Triage'), ('CONTAINMENT', 'Containment'), ('ERADICATION', 'Eradication'), ('RECOVERY', 'Recovery'), ('REVIEW', 'Post-Incident Review')], default='TRIAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='playbook',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incidentartifact',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='myapp.incident'),
        ),
        migrations.AddField(
            model_name='incidentartifact',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
